[manifest]
version = "1.0.0"

# function to allow booster packs and vouchers to appear in the shop
# taken directly from entropy with minor changes
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
for _,v in ipairs(SMODS.ConsumableType.obj_buffer) do
    total_rate = total_rate + G.GAME[v:lower()..'_rate']
end
'''
position = 'after'
match_indent = true
payload = '''
-- bof patch
if G.GAME.booster_rate then total_rate = total_rate + G.GAME.booster_rate end
if G.GAME.voucher_rate then total_rate = total_rate + G.GAME.voucher_rate end
-- patch end
'''

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
for _, v in ipairs(SMODS.ConsumableType.obj_buffer) do
    if not (v == 'Tarot' or v == 'Planet' or v == 'Spectral') then
        table.insert(rates, { type = v, val = G.GAME[v:lower()..'_rate'] })
    end
end
'''
position = 'before'
match_indent = true
payload = '''
-- bof patch
if G.GAME.booster_rate then
    table.insert(rates, { type = "Booster", val = G.GAME.booster_rate })
end
if G.GAME.voucher_rate then
    table.insert(rates, { type = "Voucher", val = G.GAME.voucher_rate })
end
-- patch end
'''

# give packs and vouchers in shop proper controller actions
# keep the generic joker-shop buy action for other cards
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
    if card.area == G.shop_jokers and G.shop_jokers then --Add a buy button
'''
position = 'before'
match_indent = true
payload = '''
-- bof patch
    if card.area == G.shop_jokers and G.shop_jokers and card.ability.set == 'Booster' then
        base_attach.children.redeem = G.UIDEF.card_focus_button{
            card = card, parent = base_attach, type = 'buy',
            func = 'can_open', button = 'open_booster', card_width = card_width*0.85
        }
    elseif card.area == G.shop_jokers and G.shop_jokers and card.ability.set == 'Voucher' then
        base_attach.children.redeem = G.UIDEF.card_focus_button{
            card = card, parent = base_attach, type = 'buy',
            func = 'can_redeem', button = 'redeem_from_shop', card_width = card_width*0.85
        }
    end
'''
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
    if card.area == G.shop_jokers and G.shop_jokers then --Add a buy button
'''
position = 'at'
match_indent = true
payload = '''
-- bof patch
    if card.area == G.shop_jokers and G.shop_jokers and card.ability.set ~= 'Booster' and card.ability.set ~= 'Voucher' then --Add a buy button
'''