[manifest]
version = "1.0.0"
dump_lua = true

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''-- TARGET : Add extra conditions here'''
position = "after"
match_indent = true
payload = '''
-- patched by bundles of fun
if self.config and self.config.center and self.config.center.key == "j_bof_fnesen" then
    return true
end
'''

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = '''if specific_vars and specific_vars.debuffed and not res.replace_debuff then'''
position = "at"
match_indent = true
payload = '''
    if specific_vars and specific_vars.debuffed and not res.replace_debuff and self.config and self.config.center and self.config.center.key ~= "j_bof_fnesen" then
'''