[manifest]
version = "1.0.0"
priority = 4.2069e10
dump_lua = true

# lang mod (pluralization & ordinalization) for older smods
# right from cryptid
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''
assembled_string = assembled_string..(type(subpart) == 'string' and subpart or format_ui_value(args.vars[tonumber(subpart[1])]) or 'ERROR')
'''
position = "at"
match_indent = true
payload = '''
-- bof patch
assembled_string = assembled_string..(type(subpart) == 'string' and subpart or (BundlesOfFun.process_ordinal and BundlesOfFun.process_ordinal(subpart[1], args.vars)) or (BundlesOfFun.pluralize and BundlesOfFun.pluralize(subpart[1], args.vars)) or format_ui_value(args.vars[tonumber(subpart[1])]) or 'ERROR')
-- patch end
'''

# prev but for newer smods
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''
assembled_string = assembled_string..(type(subpart) == 'string' and subpart or format_ui_value(args.vars[tonumber(subpart[1])]) or 'ERROR')
'''
position = "at"
match_indent = true
payload = '''
-- bof patch
assembled_string = assembled_string..(type(subpart) == 'string' and subpart or (BundlesOfFun.process_ordinal and BundlesOfFun.process_ordinal(subpart[1], args.vars)) or (BundlesOfFun.pluralize and BundlesOfFun.pluralize(subpart[1], args.vars)) or format_ui_value(args.vars[tonumber(subpart[1])]) or 'ERROR')
-- patch end
'''

# collection ui needs to show dynamic tallies
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "{n=G.UIT.T, config={scale = 0.35,text = args.count.tally..' / '..args.count.of, colour = args.text_colour}}"
position = "at"
match_indent = true
payload = '''
-- bof patch
{ n = G.UIT.T, config = { scale = 0.35, ref_table = args.count, ref_value = "display", colour = args.text_colour } }
-- patch end
'''

# hide card limit info_queue for bof items
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
match_indent = true
position = 'at'
pattern = '''
if not hide_desc and card and card.ability and (card.ability.extra_slots_used or 0) ~= 0 then
'''
payload = '''
-- bof patch
if not hide_desc and card and card.ability and (card.ability.extra_slots_used or 0) ~= 0 and not (card.config.center and card.config.center.key and string.find(card.config.center.key, "bof_")) then
-- patch end
'''

# prev cont.
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
match_indent = true
position = 'at'
pattern = '''
if not hide_desc and card and card.ability and (card.ability.card_limit or 0) ~= 0 then
'''
payload = '''
-- bof patch
if not hide_desc and card and card.ability and (card.ability.card_limit or 0) ~= 0 and not (card.config.center and card.config.center.key and string.find(card.config.center.key, "bof_")) then
-- patch end
'''

# fix troubadour mod for bundles of fun
[[patches]]
[patches.pattern]
target = '=[SMODS Troubadour "src/items/wider_collection.lua"]'
position = 'at'
match_indent = true
pattern = '''
local amt = #TRO.utils.filter(G.P_CENTER_POOLS[con.key], function(v) return not v.no_collection end)
'''
payload = '''
-- bof patch
local amt = 0
for _, v in pairs(G.P_CENTER_POOLS[con.key]) do
  local no_col = v.no_collection
  if no_col then
    if type(no_col) == "function" then
      if not no_col() then amt = amt + 1 end
    elseif not no_col then
      amt = amt + 1
    end
  else
    amt = amt + 1
  end
end
-- patch end
'''

# make it so that fossilized can display the negative consumable {T:}
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''
T.vars = {}
'''
position = "after"
match_indent = true
payload = '''
-- bof patch
T.config = part.control.T_config_extra and {extra = part.control.T_config_extra}
-- patch end
'''
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils/run_select.lua"]'''
pattern = '''
key = part.control.T,
'''
position = "after"
match_indent = true
payload = '''
-- bof patch
config = part.control.T_config_extra and {extra = part.control.T_config_extra},
-- patch end
'''