[manifest]
version = "1.0.0"
dump_lua = true

# pianoman gets more choices
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "local _size = *"
position = "after"
match_indent = true
payload = '''
-- patched by bundles of fun
if G.GAME.bof_pianoman_unlimited_boosters and not (G.GAME.jest_change_booster_options and (G.GAME.jest_change_booster_options.trigger or G.GAME.jest_change_booster_options.pack_choices == "unlimited")) then
    G.GAME.pack_choices = _size
end
'''