[manifest]
version = "1.0.0"
dump_lua = true

# risk update function to disable rightmost joker at all times
[[patches]] 
[patches.pattern]
target = "card.lua"
pattern = "function Card:update(dt)"
position = "after"
payload = '''
-- patched by bundles of fun
    if G.jokers and self.area == G.jokers and G.GAME and G.GAME.blind and G.GAME.blind.name == "The Risk" and not G.GAME.blind.disabled then
        local rightmost = self == G.jokers.cards[#G.jokers.cards]
        if self.debuff ~= rightmost then
            self:set_debuff(rightmost)
        end
        if rightmost then
            G.GAME.bof_risk_joker = self
        end
    elseif G.GAME and G.GAME.bof_risk_joker == self and self.debuff then
        self:set_debuff(false)
        G.GAME.bof_risk_joker = nil
    end
'''
match_indent = true